# Generated by Django 4.1.4 on 2023-02-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_descr_blog_desc_alter_blog_datestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.CharField(blank='2:14:34 am', max_length=225, null=True),
        ),
    ]
