# Generated by Django 4.1.4 on 2023-02-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.CharField(blank=True, default='2:18:15 am', max_length=225, null=True),
        ),
    ]
