# Generated by Django 4.1.4 on 2023-02-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blog_timestamp_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.CharField(blank=True, default='1:43:18 am', max_length=225, null=True),
        ),
    ]
